DELETE FROM Tipo_Cerveza *;

DELETE FROM Receta *;

INSERT INTO Receta (cod_rece, nombre_rece)
    VALUES (0, ' Receta para cervezas de tipo Lager'),
    (1, ' Receta para cervezas de tipo Ale'),
    (2, ' Receta para cervezas de tipo De Trigo'),
    (3, ' Receta para cervezas de tipo Bock'),
    (4, ' Receta para cervezas de tipo Eisbock'),
    (5, ' Receta para cervezas de tipo Pale Ale'),
    (6, ' Receta para cervezas de tipo Indian Pale Ale'),
    (7, ' Receta para cervezas de tipo English Bitter'),
    (8, ' Receta para cervezas de tipo Dark Ales'),
    (9, ' Receta para cervezas de tipo Stout'),
    (10, 'Receta para cervezas de tipo Porter'),
    (11, 'Receta para cervezas de tipo Belgas'),
    (12, 'Receta para cervezas de tipo Abadia'),
    (13, 'Receta para cervezas de tipo Trapense'),
    (14, 'Receta para cervezas de tipo Ambar'),
    (15, 'Receta para cervezas de tipo Flamenca'),
    (16, 'Receta para cervezas de tipo Pilsener'),
    (17, 'Receta para cervezas de tipo American Amber Ale'),
    (18, 'Receta para cervezas de tipo American IPA'),
    (19, 'Receta para cervezas de tipo American Pale Ale'),
    (20, 'Receta para cervezas de tipo Belgian Dubbel'),
    (21, 'Receta para cervezas de tipo Belgian Golden Strong Ale'),
    (22, 'Receta para cervezas de tipo Belgian Specialty Ale'),
    (23, 'Receta para cervezas de tipo Orval'),
    (24, 'Receta para cervezas de tipo Chouffe'),
    (25, 'Receta para cervezas de tipo Blond Trappist'),
    (26, 'Receta para cervezas de tipo Table Beer'),
    (27, 'Receta para cervezas de tipo Artisanal Blond'),
    (28, 'Receta para cervezas de tipo Artisanal Amber'),
    (29, 'Receta para cervezas de tipo Artisanal Brown'),
    (30, 'Receta para cervezas de tipo Belgian Barleywine'),
    (31, 'Receta para cervezas de tipo Trappist Quadrupel'),
    (32, 'Receta para cervezas de tipo Belgian Spiced Christmass Beer'),
    (33, 'Receta para cervezas de tipo Belgian IPA'),
    (34, 'Receta para cervezas de tipo Strong Dark Saison'),
    (35, 'Receta para cervezas de tipo Flanders Red'),
    (36, 'Receta para cervezas de tipo Flanders Brown'),
    (37, 'Receta para cervezas de tipo Blonde Ale'),
    (38, 'Receta para cervezas de tipo Bohemian Pilsener'),
    (39, 'Receta para cervezas de tipo Dry Stout'),
    (40, 'Receta para cervezas de tipo Düsseldorf Altbier'),
    (41, 'Receta para cervezas de tipo English Pale Ale'),
    (42, 'Receta para cervezas de tipo Extra-Strong Bitter'),
    (43, 'Receta para cervezas de tipo Fruit Lambic'),
    (44, 'Receta para cervezas de tipo Imperial IPA'),
    (45, 'Receta para cervezas de tipo Imperial Stout'),
    (46, 'Receta para cervezas de tipo Munich Helles'),
    (47, 'Receta para cervezas de tipo Oktoberfest-Marzen'),
    (48, 'Receta para cervezas de tipo Red Ale'),
    (49, 'Receta para cervezas de tipo Irish Red Ale'),
    (50, 'Receta para cervezas de tipo Schwarzbier'),
    (51, 'Receta para cervezas de tipo Sweet Stout'),
    (52, 'Receta para cervezas de tipo Weizen-Weissbier'),
    (53, 'Receta para cervezas de tipo Witbier');

INSERT INTO Tipo_Cerveza (cod_tipo_cerv, nombre_tipo_cerv, fk_receta, fk_tipo_cerv)
    VALUES (0, 'Lager', 0, NULL),
    (1, 'Ale', 1, NULL),
    (2, 'De Trigo', 2, 2),
    (3, 'Bock', 3, 0),
    (4, 'Eisbock', 4, 3),
    (5, 'Pale Ale', 5, 1),
    (6, 'Indian Pale Ale', 6, 5),
    (7, 'English Bitter', 7, 5),
    (8, 'Dark Ales', 8, 1),
    (9, 'Stout', 9, 8),
    (10, 'Porter', 10, 8),
    (11, 'Belgas', 11, 1),
    (12, 'Abadia', 12, 11),
    (13, 'Trapense', 13, 11),
    (14, 'Ambar', 14, 11),
    (15, 'Flamenca', 15, 11),
    (16, 'Pilsener', 16, 1),
    (17, 'American Amber Ale', 17, 1),
    (18, 'American IPA', 18, 6),
    (19, 'American Pale Ale', 19, 5),
    (20, 'Belgian Dubbel', 20, 1),
    (21, 'Belgian Golden Strong Ale', 21, 1),
    (22, 'Belgian Specialty Ale', 22, 1),
    (23, 'Orval', 23, 22),
    (24, 'Chouffe', 24, 22),
    (25, 'Blond Trappist', 25, 22),
    (26, 'Table Beer', 26, 22),
    (27, 'Artisanal Blond', 27, 22),
    (28, 'Artisanal Amber', 28, 22),
    (29, 'Artisanal Brown', 29, 22),
    (30, 'Belgian Barleywine', 30, 22),
    (31, 'Trappist Quadrupel', 31, 22),
    (32, 'Belgian Spiced Christmass Beer', 32, 22),
    (33, 'Belgian IPA', 33, 22),
    (34, 'Strong Dark Saison', 34, 22),
    (35, 'Flanders Red', 35, 22),
    (36, 'Flanders Brown', 36, 22),
    (37, 'Blonde Ale', 37, 1),
    (38, 'Bohemian Pilsener', 38, 16),
    (39, 'Dry Stout', 39, 9),
    (40, 'Düsseldorf Altbier', 40, 1),
    (41, 'English Pale Ale', 41, 5),
    (42, 'Extra-Strong Bitter', 42, 5),
    (43, 'Fruit Lambic', 43, 1),
    (44, 'Imperial IPA', 44, 6),
    (45, 'Imperial Stout', 45, 9),
    (46, 'Munich Helles', 46, 0),
    (47, 'Oktoberfest-Marzen', 47, 0),
    (48, 'Red Ale', 48, 1),
    (49, 'Irish Red Ale', 49, 48),
    (50, 'Schwarzbier', 50, 0),
    (51, 'Sweet Stout', 51, 9),
    (52, 'Weizen-Weissbier', 52, 2),
    (53, 'Witbier', 53, 2);
