INSERT INTO BANCO (nombre_banc)
    VALUES ('Banco de Venezuela'),
    ('Bancamiga'),
    ('Banesco'),
    ('Banco Mercantil'),
    ('Banco Nacional de Crédito (BNC)'),
    ('Banco del Tesoro'),
    ('Banco Exterior'),
    ('Banco Provincial'),
    ('Banco Caroní'),
    ('Banco Sofitasa'),
    ('Banca Amiga'),
    ('Banco Agrícola de Venezuela'),
    ('Banco Bicentenario'),
    ('Banco del Caribe');
